apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: qa
spec:
  replicas: 5 # will create 5 pods replicas/duplicates.
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80