apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-sidecar
spec:
  containers:
    - name: nginx-container # main container
      image: nginx:latest
      volumeMounts: # to mount the volume with nginx
      - name: log-volume
        mountPath:  /var/log/nginx # files inside the path should be kept inside the log-volume.

    - name: sode-car-container # side car container
      image: busybox:latest
      command: [ "/bin/sh", "-c", "tail -f /var/log/nginx/access.log" ] # to read the access.log file
      volumeMounts: # to mount the volume with nginx
      - name: log-volume
        mountPath:  /var/log/nginx

  volumes:
  - name: log-volume # name for the volume
    emptyDir: {} # Create the volume inside the POD